spring:
  rabbitmq:
    publisher-confirms: true
    addresses: rabbit.ops.com:8889
    username: tbbdev
    password: tbbdev
    virtual-host: /tbbdev
    listener:
      simple:
        acknowledge-mode: manual
        max-concurrency: 8
        concurrency: 1
